### ISSUE TITLE
issue with getCompartments and getArrayABsignal

### ISSUE THREAD

**Issue by Al3n70rn** [biobenkj/compartmap#4] opened 2019-09-06 17:12 UTC
Hi,

When I use the vignette example or the example in getArrayABsignal there are several errors:

```R

library(compartmap)
data("meth_array_450k_chr14", package = "compartmap")
array_compartments <- getArrayABsignal(array.data.chr14, parallel=F, chr="chr14", bootstrap=F, genome="hg19", array.type="hm450")

Loading required package: minfi
Loading required package: bumphunter
Loading required package: foreach
Loading required package: iterators
Loading required package: locfit
locfit 1.5-9.1 	 2013-03-22
Setting options('download.file.method.GEOquery'='auto')
Setting options('GEOquery.inmemory.gpl'=FALSE)

Attaching package: ‘minfi’

The following object is masked from ‘package:bsseq’:

    getMeth

Filtering to open sea CpG loci...
Converting to squeezed M-values.
Imputing missing values.
Dropping samples with >80% NAs.
Imputing missing data with kNN.
Cluster size 3384 broken into 2771 613 
Cluster size 2771 broken into 1052 1719 
Done cluster 1052 
Cluster size 1719 broken into 476 1243 
Done cluster 476 
Done cluster 1243 
Done cluster 1719 
Done cluster 2771 
Done cluster 613 
Working on naive.1
Computing compartments for chr14
Calculating correlations...
Done...
Calculating eigenvectors.
Smoothing eigenvector.
Done smoothing.
Working on rTreg.2
Computing compartments for chr14
Calculating correlations...
Done...
Calculating eigenvectors.
Smoothing eigenvector.
Done smoothing.
Working on act_naive.3
Computing compartments for chr14
Calculating correlations...
Done...
Calculating eigenvectors.
Smoothing eigenvector.
Done smoothing.
Working on naive.4
Computing compartments for chr14
Calculating correlations...
Done...
Calculating eigenvectors.
Smoothing eigenvector.
Done smoothing.
Working on act_naive.5
Computing compartments for chr14
Calculating correlations...
Done...
Calculating eigenvectors.
Smoothing eigenvector.
Done smoothing.
Working on act_rTreg.6
Computing compartments for chr14
Calculating correlations...
Done...
Calculating eigenvectors.
Smoothing eigenvector.
Done smoothing.
Working on naive.7
Computing compartments for chr14
Calculating correlations...
Done...
Calculating eigenvectors.
Smoothing eigenvector.
Done smoothing.
Working on rTreg.8
Computing compartments for chr14
Calculating correlations...
Done...
Calculating eigenvectors.
Smoothing eigenvector.
Done smoothing.
Working on act_naive.9
Computing compartments for chr14
Calculating correlations...
Done...
Calculating eigenvectors.
Smoothing eigenvector.
Done smoothing.
Working on act_rTreg.10
Computing compartments for chr14
Calculating correlations...
Done...
Calculating eigenvectors.
Smoothing eigenvector.
Done smoothing.
Working on birth.11
Computing compartments for chr14
Calculating correlations...
Done...
Calculating eigenvectors.
Smoothing eigenvector.
Done smoothing.
Error in as(objects[[1L]], "CompressedGRangesList", strict = FALSE) : 
  no method or default for coercing “SimpleGRangesList” to “CompressedGRangesList”

# In addition when I use 
array_compartments <- getCompartments(array.data.chr14, type = "array", parallel = FALSE, chrs = "chr14")

Error in getCompartments(arrau.data.ch14, type = "array", parallel = FALSE, : 
could not find function "getComparments"

sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.10

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.3.3.so

locale:
 [1] LC_CTYPE=fr_FR.UTF-8       LC_NUMERIC=C               LC_TIME=fr_FR.UTF-8        LC_COLLATE=fr_FR.UTF-8    
 [5] LC_MONETARY=fr_FR.UTF-8    LC_MESSAGES=fr_FR.UTF-8    LC_PAPER=fr_FR.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=fr_FR.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] parallel  stats4    stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] minfi_1.31.1                             bumphunter_1.27.0                       
 [3] locfit_1.5-9.1                           iterators_1.0.12                        
 [5] foreach_1.4.7                            compartmap_1.65.6                       
 [7] bsseq_1.21.1                             BiocSingular_1.1.5                      
 [9] BSgenome.Mmusculus.UCSC.mm9_1.4.0        Mus.musculus_1.3.1                      
[11] TxDb.Mmusculus.UCSC.mm10.knownGene_3.4.7 org.Mm.eg.db_3.8.2                      
[13] BSgenome.Hsapiens.UCSC.hg38_1.4.1        BSgenome_1.53.2                         
[15] rtracklayer_1.45.5                       Biostrings_2.53.2                       
[17] XVector_0.25.0                           Homo.sapiens_1.3.1                      
[19] TxDb.Hsapiens.UCSC.hg19.knownGene_3.2.2  org.Hs.eg.db_3.8.2                      
[21] GO.db_3.8.2                              OrganismDbi_1.27.1                      
[23] GenomicFeatures_1.37.4                   AnnotationDbi_1.47.1                    
[25] RaggedExperiment_1.9.1                   SummarizedExperiment_1.15.8             
[27] DelayedArray_0.11.4                      BiocParallel_1.19.2                     
[29] matrixStats_0.54.0                       Biobase_2.45.1                          
[31] GenomicRanges_1.37.15                    GenomeInfoDb_1.21.1                     
[33] IRanges_2.19.14                          S4Vectors_0.23.21                       
[35] BiocGenerics_0.31.5                     

loaded via a namespace (and not attached):
  [1] backports_1.1.4          BiocFileCache_1.9.1      plyr_1.8.4               igraph_1.2.4.1          
  [5] lazyeval_0.2.2           splines_3.6.1            ggplot2_3.2.1            digest_0.6.20           
  [9] viridis_0.5.1            magrittr_1.5             memoise_1.1.0            limma_3.41.15           
 [13] readr_1.3.1              annotate_1.63.0          R.utils_2.9.0            askpass_1.1             
 [17] siggenes_1.59.0          prettyunits_1.0.2        colorspace_1.4-1         blob_1.2.0              
 [21] rappdirs_0.3.1           dplyr_0.8.3              crayon_1.3.4             RCurl_1.95-4.12         
 [25] graph_1.63.0             genefilter_1.67.1        GEOquery_2.53.0          zeallot_0.1.0           
 [29] impute_1.59.0            survival_2.44-1.1        glue_1.3.1               registry_0.5-1          
 [33] gtable_0.3.0             zlibbioc_1.31.0          Rhdf5lib_1.7.4           HDF5Array_1.13.5        
 [37] scales_1.0.0             DBI_1.0.0                rngtools_1.4             bibtex_0.4.2            
 [41] Rcpp_1.0.2               viridisLite_0.3.0        xtable_1.8-4             progress_1.2.2          
 [45] bit_1.1-14               rsvd_1.0.2               mclust_5.4.5             preprocessCore_1.47.1   
 [49] httr_1.4.1               RColorBrewer_1.1-2       pkgconfig_2.0.2          reshape_0.8.8           
 [53] XML_3.98-1.20            R.methodsS3_1.7.1        dbplyr_1.4.2             tidyselect_0.2.5        
 [57] rlang_0.4.0              munsell_0.5.0            tools_3.6.1              RSQLite_2.1.2           
 [61] stringr_1.4.0            bit64_0.9-7              beanplot_1.2             scrime_1.3.5            
 [65] purrr_0.3.2              RANN_2.6.1               nlme_3.1-141             pbapply_1.4-2           
 [69] RBGL_1.61.0              doRNG_1.7.1              nor1mix_1.3-0            R.oo_1.22.0             
 [73] xml2_1.2.2               biomaRt_2.41.8           compiler_3.6.1           rstudioapi_0.10         
 [77] curl_4.0                 tibble_2.1.3             stringi_1.4.3            lattice_0.20-38         
 [81] Matrix_1.2-17            permute_0.9-5            multtest_2.41.0          vctrs_0.2.0             
 [85] pillar_1.4.2             BiocManager_1.30.4       data.table_1.12.2        bitops_1.0-6            
 [89] irlba_2.3.3              R6_2.4.0                 gridExtra_2.3            codetools_0.2-16        
 [93] MASS_7.3-51.4            gtools_3.8.1             assertthat_0.2.1         rhdf5_2.29.0            
 [97] openssl_1.4.1            pkgmaker_0.27            withr_2.1.2              GenomicAlignments_1.21.5
[101] Rsamtools_2.1.4          GenomeInfoDbData_1.2.1   hms_0.5.1                quadprog_1.5-7          
[105] grid_3.6.1               tidyr_0.8.3              base64_2.0               DelayedMatrixStats_1.7.1
[109] illuminaio_0.27.1   

```

Could you help me ?

Best,
A

**Comment by biobenkj** [comment] 2019-09-10 21:55
Hi @Al3n70rn thanks so much for trying compartmap. We are in the process of major changes to the API, including deprecating the getCompartments wrapper function. All of the changes and bug fixes will be pushed to Bioc-devel next week. One of the changes is the vignette is way out of date at this point, as you've discovered :). Would you be willing to wait until then? Thanks again.

**Comment by biobenkj** [comment] 2019-09-10 22:08
Also, it looks like it's failing to create the RaggedExperiment object. There have been several bugs lately that have been cropping up with SummarizedExperiment objects and wonder if RaggedExperiment is also impacted.

for me:
```
> library(compartmap)
> data("meth_array_450k_chr14", package = "compartmap")
Loading required package: minfi
Loading required package: bumphunter
Loading required package: foreach
Loading required package: iterators
Loading required package: locfit
locfit 1.5-9.1 	 2013-03-22
Setting options('download.file.method.GEOquery'='auto')
Setting options('GEOquery.inmemory.gpl'=FALSE)

Attaching package: ‘minfi’

The following object is masked from ‘package:bsseq’:

    getMeth

> array_compartments <- getArrayABsignal(array.data.chr14, parallel=F, chr="chr14", bootstrap=F, genome="hg19", array.type="hm450")
Filtering to open sea CpG loci...
Converting to squeezed M-values.
Imputing missing values.
Dropping samples with >80% NAs.
Imputing missing data with kNN.
Cluster size 3384 broken into 2771 613 
Cluster size 2771 broken into 1052 1719 
Done cluster 1052 
Cluster size 1719 broken into 476 1243 
Done cluster 476 
Done cluster 1243 
Done cluster 1719 
Done cluster 2771 
Done cluster 613 
Working on naive.1
Computing compartments for chr14
Calculating correlations...
Done...
Calculating eigenvectors.
Smoothing eigenvector.
Done smoothing.
Working on rTreg.2
Computing compartments for chr14
Calculating correlations...
Done...
Calculating eigenvectors.
Smoothing eigenvector.
Done smoothing.
Working on act_naive.3
Computing compartments for chr14
Calculating correlations...
Done...
Calculating eigenvectors.
Smoothing eigenvector.
Done smoothing.
Working on naive.4
Computing compartments for chr14
Calculating correlations...
Done...
Calculating eigenvectors.
Smoothing eigenvector.
Done smoothing.
Working on act_naive.5
Computing compartments for chr14
Calculating correlations...
Done...
Calculating eigenvectors.
Smoothing eigenvector.
Done smoothing.
Working on act_rTreg.6
Computing compartments for chr14
Calculating correlations...
Done...
Calculating eigenvectors.
Smoothing eigenvector.
Done smoothing.
Working on naive.7
Computing compartments for chr14
Calculating correlations...
Done...
Calculating eigenvectors.
Smoothing eigenvector.
Done smoothing.
Working on rTreg.8
Computing compartments for chr14
Calculating correlations...
Done...
Calculating eigenvectors.
Smoothing eigenvector.
Done smoothing.
Working on act_naive.9
Computing compartments for chr14
Calculating correlations...
Done...
Calculating eigenvectors.
Smoothing eigenvector.
Done smoothing.
Working on act_rTreg.10
Computing compartments for chr14
Calculating correlations...
Done...
Calculating eigenvectors.
Smoothing eigenvector.
Done smoothing.
Working on birth.11
Computing compartments for chr14
Calculating correlations...
Done...
Calculating eigenvectors.
Smoothing eigenvector.
Done smoothing.
> array_compartments
class: RaggedExperiment 
dim: 968 11 
assays(2): pc compartments
rownames: NULL
colnames(11): naive.1 rTreg.2 ... act_rTreg.10 birth.11
colData names(10): Sample_Name Sample_Well ... Basename filenames
```

and 

```
> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.5

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] parallel  stats4    stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] minfi_1.30.0                             bumphunter_1.26.0                        locfit_1.5-9.1                          
 [4] iterators_1.0.12                         foreach_1.4.7                            compartmap_1.65.6                       
 [7] bsseq_1.20.0                             BiocSingular_1.0.0                       BSgenome.Mmusculus.UCSC.mm9_1.4.0       
[10] Mus.musculus_1.3.1                       TxDb.Mmusculus.UCSC.mm10.knownGene_3.4.7 org.Mm.eg.db_3.8.2                      
[13] BSgenome.Hsapiens.UCSC.hg38_1.4.1        BSgenome_1.52.0                          rtracklayer_1.44.3                      
[16] Biostrings_2.52.0                        XVector_0.24.0                           Homo.sapiens_1.3.1                      
[19] TxDb.Hsapiens.UCSC.hg19.knownGene_3.2.2  org.Hs.eg.db_3.8.2                       GO.db_3.8.2                             
[22] OrganismDbi_1.26.0                       GenomicFeatures_1.36.4                   AnnotationDbi_1.46.1                    
[25] RaggedExperiment_1.8.0                   SummarizedExperiment_1.14.1              DelayedArray_0.10.0                     
[28] BiocParallel_1.18.1                      matrixStats_0.54.0                       Biobase_2.44.0                          
[31] GenomicRanges_1.36.0                     GenomeInfoDb_1.20.0                      IRanges_2.18.2                          
[34] S4Vectors_0.22.0                         BiocGenerics_0.30.0                     

loaded via a namespace (and not attached):
  [1] backports_1.1.4          plyr_1.8.4               igraph_1.2.4.1           lazyeval_0.2.2           splines_3.6.1           
  [6] ggplot2_3.2.1            digest_0.6.20            viridis_0.5.1            magrittr_1.5             memoise_1.1.0           
 [11] limma_3.40.6             readr_1.3.1              annotate_1.62.0          R.utils_2.9.0            askpass_1.1             
 [16] siggenes_1.58.0          prettyunits_1.0.2        colorspace_1.4-1         blob_1.2.0               dplyr_0.8.3             
 [21] crayon_1.3.4             RCurl_1.95-4.12          graph_1.62.0             genefilter_1.66.0        GEOquery_2.52.0         
 [26] zeallot_0.1.0            impute_1.58.0            survival_2.44-1.1        glue_1.3.1               registry_0.5-1          
 [31] gtable_0.3.0             zlibbioc_1.30.0          Rhdf5lib_1.6.0           HDF5Array_1.12.2         scales_1.0.0            
 [36] DBI_1.0.0                rngtools_1.4             bibtex_0.4.2             Rcpp_1.0.2               viridisLite_0.3.0       
 [41] xtable_1.8-4             progress_1.2.2           bit_1.1-14               rsvd_1.0.2               mclust_5.4.5            
 [46] preprocessCore_1.46.0    httr_1.4.1               RColorBrewer_1.1-2       pkgconfig_2.0.2          reshape_0.8.8           
 [51] XML_3.98-1.20            R.methodsS3_1.7.1        tidyselect_0.2.5         rlang_0.4.0              munsell_0.5.0           
 [56] tools_3.6.1              RSQLite_2.1.2            stringr_1.4.0            bit64_0.9-7              beanplot_1.2            
 [61] scrime_1.3.5             purrr_0.3.2              RANN_2.6.1               nlme_3.1-141             pbapply_1.4-2           
 [66] RBGL_1.60.0              doRNG_1.7.1              nor1mix_1.3-0            R.oo_1.22.0              xml2_1.2.2              
 [71] biomaRt_2.40.4           compiler_3.6.1           rstudioapi_0.10          tibble_2.1.3             stringi_1.4.3           
 [76] lattice_0.20-38          Matrix_1.2-17            permute_0.9-5            multtest_2.40.0          vctrs_0.2.0             
 [81] pillar_1.4.2             BiocManager_1.30.4       data.table_1.12.2        bitops_1.0-6             irlba_2.3.3             
 [86] R6_2.4.0                 gridExtra_2.3            codetools_0.2-16         MASS_7.3-51.4            gtools_3.8.1            
 [91] assertthat_0.2.1         rhdf5_2.28.0             openssl_1.4.1            pkgmaker_0.27            withr_2.1.2             
 [96] GenomicAlignments_1.20.1 Rsamtools_2.0.0          GenomeInfoDbData_1.2.1   hms_0.5.1                quadprog_1.5-7          
[101] grid_3.6.1               tidyr_0.8.3              base64_2.0               DelayedMatrixStats_1.6.0 illuminaio_0.26.0       
```

So I wonder what happens if you roll back to RaggedExperiment 1.8.0 and SummarizedExperiment 1.14.1? This is a huge pain point lately for our group as well.

**Comment by biobenkj** [comment] 2019-09-11 01:14
Well, not sure this is consolation or not, but if I update to Bioc devel, I can make it fail with the same error you are getting as well. The less useful part is that S4Vectors appears to be failing and may be the root cause of things. I say this because if I try to import minfi after installing the devel versions of BiocGenerics and S4Vectors, I get:

```
> library(minfi)
Error: package or namespace load failed for 'minfi':
 objects 'rowSums', 'colSums', 'rowMeans', 'colMeans' are not exported by 'namespace:S4Vectors'
In addition: Warning messages:
1: replacing previous import 'S4Vectors::splitAsList' by 'IRanges::splitAsList' when loading 'minfi' 
2: replacing previous import 'BiocGenerics::type' by 'DelayedArray::type' when loading 'minfi'
```

**Comment by Al3n70rn** [comment] 2019-09-11 16:46
Thanks! I did roll back to Bioc 3.9 and everything works perfectly.

Actually, I prefer the compartmap v1.65.6 because the parallel analysis is much better included than in the previous version and to analyze large datasets is highly desirable!

Best regards,

**Comment by biobenkj** [comment] 2019-09-11 18:41
Great! Let me know if you run into other bugs. One thing that will probably be stripped out of the version that goes into release is the parallelization of boot strapping. It's remarkably flaky right now and I don't know why. All of this is still a work in progress. Thanks again for giving it a shot!

Cheers

**Comment by biobenkj** [comment] 2019-10-09 13:17
Reopening the issue since this is a breaking change in the upcoming Bioconductor 3.10 release.

Bioconductor/RaggedExperiment#24

**Comment by biobenkj** [comment] 2019-10-09 21:48
closing the issue now after making the explicit fix of as(mylist, "CompressedGRangesList") in v1.65.71

**Closed by biobenkj** 2019-10-09 21:48 UTC
